services:
  app:
    container_name: cathop_app
    restart: unless-stopped
    image: 'ghcr.io/sbeltranc/cathop:latest'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - cathop_network

  db:
    container_name: cathop_db
    restart: unless-stopped
    image: "postgres:latest"
    volumes:
      - cathop_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s
    networks:
      - cathop_network
  
  tunnel:
    container_name: cathop_tunnel
    image: "cloudflare/cloudflared:latest"
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_ZERO_TRUST_TOKEN}
    networks:
      - cathop_network
      
volumes:
  cathop_db_data:
    external: false
      
networks:
  cathop_network: null